// MERLIN, ASSASSIN, PERCIVAL, MORGANA, MORDRED, OBERON, GOOD, EVIL;

export enum CharacterType {
    MERLIN = "MERLIN",
    ASSASSIN = "ASSASSIN",
    PERCIVAL = "PERCIVAL",
    MORGANA = "MORGANA",
    MORDRED = "MORDRED",
    OBERON = "OBERON",
    GOOD = "GOOD",
    EVIL = "EVIL",
}