// NOT_STARTED, IN_PROGRESS, ASSASSIN_FLOP, EVIL_WON_WITH_ASSASSINATION, EVIL_WON_WITH_QUEST, GOOD_WON

export enum GameStatus{
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    ASSASSIN_FLOP = "ASSASSIN_FLOP",
    EVIL_WON_WITH_ASSASSINATION = "EVIL_WON_WITH_ASSASSINATION",
    EVIL_WON_WITH_QUEST = "EVIL_WON_WITH_QUEST",
    GOOD_WON = "GOOD_WON"
}