// INITIAL_TEAM, DISCUSSING, FINAL_TEAM_VOTING, FINAL_TEAM_VOTING_SUCCESS, FINAL_TEAM_VOTING_FAIL, QUEST_SUCCESS, QUEST_FAIL

export enum RoundStatus {
    INITIAL_TEAM = "INITIAL_TEAM",
    DISCUSSING = "DISCUSSING",
    FINAL_TEAM_VOTING = "FINAL_TEAM_VOTING",
    FINAL_TEAM_VOTING_SUCCESS = "FINAL_TEAM_VOTING_SUCCESS",
    FINAL_TEAM_VOTING_FAIL = "FINAL_TEAM_VOTING_FAIL",
    QUEST_SUCCESS = "QUEST_SUCCESS",
    QUEST_FAIL = "QUEST_FAIL",
}