// MISSION_SUCCESS, MISSION_FAILED, MISSION_PENDING

export enum TeamMemberStatus {
    MISSION_SUCCESS = "MISSION_SUCCESS",
    MISSION_FAILED = "MISSION_FAILED",
    MISSION_PENDING = "MISSION_PENDING"
}